name: example
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
#publish_to: 'homepage' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #state management
  bloc: 8.1.4
  flutter_bloc: ^8.1.6

  eb_purchase:
    path: ../
  in_app_purchase: ^3.2.1

  collection: ^1.19.1

  #Device Information
  device_info_plus: ^11.2.1
  package_info_plus: ^8.1.3

  dartz:

  #dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  #data models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7


dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  #generators
  build_runner: ^2.4.14

  json_serializable: ^6.9.3
  freezed: ^2.5.8
  injectable_generator: ^2.7.0




flutter:

  uses-material-design: true
