name: eb_purchase
description: "Simplifies in-app purchase management with seamless integration for app stores, support for subscriptions, and secure transaction handling. Ideal for developers implementing reliable and user-friendly monetization solutions in Flutter applications."
version: 1.4.1
homepage: "https://github.com/basnetjiten/eb_purchases"
publish_to: none

environment:
  sdk: ">= 3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  #Billing
  in_app_purchase: ^3.2.1
  in_app_purchase_android: ^0.4.0+1
  in_app_purchase_storekit: ^0.3.21

  #Device Information
  device_info_plus: ^11.2.2
  package_info_plus: ^8.1.4


  #data models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  injectable: ^2.5.0

  collection: ^1.19.0 # flutter sdk depends on version  1.19.0
  pigeon: ^24.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  #generators
  build_runner: ^2.4.15

  json_serializable: ^6.9.4
  freezed: ^2.5.8
  injectable_generator: ^2.7.0


